"""Telematics/IoT data ingestion — parses a JSON or CSV file (as a real
insurer telematics box would normally push automatically) into a normalized
dict consumed by Context Verification, Fraud Intelligence, and Incident
Reconstruction. There's no real hardware in this project; sample files for
demoing the pipeline are generated by scripts/generate_sample_telematics.py.
"""

import csv
import json
import os
from typing import Optional

import storage

_REQUIRED_SCALAR_FIELDS = (
    "event_timestamp", "speed_kmph_at_event", "hard_braking_detected",
    "impact_g_force", "airbag_deployed",
)


def parse_telematics(file_path: str) -> dict:
    """Returns a dict shaped:
    {
      "parsed_ok": bool,
      "event_timestamp": str | None,
      "speed_kmph_at_event": float | None,
      "hard_braking_detected": bool | None,
      "impact_g_force": float | None,
      "airbag_deployed": bool | None,
      "gps_trail": [{"lat": float, "lon": float, "timestamp": str}, ...],
    }
    A CSV file is treated as GPS-trail-only (lat,lon,timestamp rows) — the
    scalar event fields are left None, same "parsed_ok + partial data" pattern
    as document_parser.py's FIR/estimate parsing.
    """
    ext = os.path.splitext(file_path)[-1].lower().lstrip(".")
    if not os.path.exists(file_path):
        return {"parsed_ok": False, "error": "File not found"}

    try:
        if ext == "json":
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            result = {field: data.get(field) for field in _REQUIRED_SCALAR_FIELDS}
            result["gps_trail"] = data.get("gps_trail") or []
            result["parsed_ok"] = True
            return result

        if ext == "csv":
            gps_trail = []
            with open(file_path, "r", encoding="utf-8", newline="") as f:
                for row in csv.DictReader(f):
                    try:
                        gps_trail.append({
                            "lat": float(row["lat"]),
                            "lon": float(row["lon"]),
                            "timestamp": row.get("timestamp", ""),
                        })
                    except (KeyError, ValueError):
                        continue
            return {
                **{field: None for field in _REQUIRED_SCALAR_FIELDS},
                "gps_trail": gps_trail,
                "parsed_ok": bool(gps_trail),
            }

        return {"parsed_ok": False, "error": f"Unsupported telematics file type: .{ext}"}
    except Exception as exc:
        return {"parsed_ok": False, "error": str(exc)}


def save_parsed_telematics(claim_id: str, result: dict) -> None:
    """Persist the parsed telematics dict so it survives past the
    investigation run, same docs/parsed_*.json pattern as document_parser.py."""
    docs_dir = storage.get_docs_dir(claim_id)
    os.makedirs(docs_dir, exist_ok=True)
    out_path = os.path.join(docs_dir, "parsed_telematics.json")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2, ensure_ascii=False)


def get_parsed_telematics(claim_id: str) -> Optional[dict]:
    path = os.path.join(storage.get_docs_dir(claim_id), "parsed_telematics.json")
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)
